### ISSUE TITLE
Doesn't work with chrome

### ISSUE THREAD

**Issue by Netzweberei** [jklmnn/imagejs#5]
Hi there,
chrome shows an error: "Refused to execute script because its MIME type ('image/gif') is not executable."
Any ideas?

Thanks in advance,
Andreas

**Comment by jklmnn** [comment]
Well, I'm glad it shows that error now. When I created this tool, chrome only showed a warning and continued executing the script. If you don't already have done, you can try to add `type="text/javascript"` to the script tag.  
Anyway browsers shouldn't execute those images at all due to security reasons. There has also been a security issue report to chrome ( https://code.google.com/p/chromium/issues/detail?id=433049 ) about that. They might have applied a patch there.
