### ISSUE TITLE
don't work with Bmp file's

### ISSUE THREAD

**Issue by ziflar** [jklmnn/imagejs#6]
thank you for this good job.
i've built imagejs from github.
it's ok for Gif file but don't work with Bmp file .
i've tested the 2 option -l and -i but alwys the same problem " don't display my js code on html".
ive run strings on the file.js.bmp generated with imagejs and i've got on the end of code this:
*/;alert("Hello\nHow are you?");
maye be */; block displaying "alert("Hello\nHow are you?");" when i call it like this : 
<script src="1.js.bmp"></script>.
please help to run it with Bmp file's

**Comment by jklmnn** [comment]
Thanks for the feedback. I'll take a look at this, as soon as I find time.

**Comment by jklmnn** [comment]
I couldn't recreate your issue. Can you give me an example of the javascript file you have used, the exact arguments you used for imagejs?
That would help me to understand what went wrong.

**Comment by ziflar** [comment]
@jklmnn my js is a simple alert : 
1.js = alert("Hello\nHow are you?");
1.bmp = [](http://www.floppycats.com/wp-content/uploads/2010/03/Bella.bmp)

**Comment by jklmnn** [comment]
Thanks for the info.
The `-l` option doesn't take any argument as it only creates a new bitmap that can be viewes as a line of pixels. It currently only works with bitmaps. Other file formats will be created but not be renderable.
I think that `-i` doesn't work on your image because it somewhere contains the ascii representation of `*/` which ends the comment that is created to contain the image data. At this point the image data is interpreted as JavaScript and creates a syntax error. That's why it doesn't work in the browser. I'm currently not sure how to work around this without manipulating the image data directly (and therefore possibly breaking the image).

NOTE: Depending on the browser you use, it doesn't work at all. [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=433049) for example has this fixed. Also Firefox with [noscript](https://addons.mozilla.org/en-US/firefox/addon/noscript/) installed won't execute these files even with JavaScript enabled. This is all because `<script>` tags that refer to files with another MIME type than `text/javascript` are considered dangerous.

**Comment by ziflar** [comment]
@jklmnn hi 
j'ai testé plusieurs bitmap images.sur [firefox 50.0.2](url) et aussi on [internet explorer.](url)
le message d'alerte comme js n'est pas affiché .
je me demande si */=0; peux resoudre le probleme
on peux procéder par la commande sed pour remplacer */; au */=0;

**Comment by jklmnn** [comment]
I have tried a manual fix. Changing `*/;` to `*/=0` didn't change anything.

As I have suspected there are several `*/` bytes in the image. Replacing them with `*//*` (which means inserting `/*` after every `*/`) did make the image executable as javascript again.
Unfortunately this somehow destroys the image and makes it look like this:
![Fix1](https://cloud.githubusercontent.com/assets/7999005/20792727/b375bf5e-b7c3-11e6-87e5-415de01304ff.png)

I have tried a second fix by not inserting two new bytes but replacing the two following bytes after `*/` with `/*`. This fixed the issue and also wasn't viewable by a human (at least I couldn't spot the difference). The resulting image looks like this:
![Fix2](https://cloud.githubusercontent.com/assets/7999005/20792981/ffafb450-b7c4-11e6-8d31-12fd82fe4a89.png)

NOTE: I have done those fixed by hand and still need to implement them. The shown images are png files converted from the original bmps since GitHub didn't allow the upload of bmp files.

**Comment by jklmnn** [comment]
I have created a fix. Can you please build from the new source and try if it works for you?

**Comment by ziflar** [comment]
@jklmnn good it's fixed 
the js message is displayed and The resulting image is undeformed
it's fixed thank you for this best tool

**Comment by ziflar** [comment]
@jklmnn on your website you say : 
# Does it support other programming languages?
It supports any language that uses // and /*...*/ for commenting.

please how to run it for example for PHP script ?

**Comment by jklmnn** [comment]
No Problem ;)
Well it works with other languages theoretically. The basic principle is that it comments non-readable bytes and non-parsable strings out.
So based on this PHP would work. But it has a speciality which is the leading `<?php` for its code. There would be two ways:
- put `<?php` in the header, which is not supported by this tool.
- put ´<?php` into the code that shall be executed. But this would print the data of the whole image before it would execute any PHP code.

To try it with PHP just replace your input JavaScript file with your PHP file.

I should change the note on the website. It is theoretically possible to support any language with those comments, but I don't actively support it.

**Comment by jklmnn** [comment]
Closing this as the original bug has been fixed.
